export const testnetCollection = [
  {
    id: 1,
    side: "White",
    material: "Bronze",
    piece: "Pawn",
    rarity: "Common",
    edition: 1,
    maxSupply: 500,
  },
  {
    id: 2,
    side: "Black",
    material: "Bronze",
    piece: "Pawn",
    rarity: "Common",
    edition: 1,
    maxSupply: 500,
  },
  {
    id: 3,
    side: "White",
    material: "Silver",
    piece: "Knight",
    rarity: "Rare",
    edition: 1,
    maxSupply: 80,
  },
  {
    id: 4,
    side: "Black",
    material: "Silver",
    piece: "Knight",
    rarity: "Rare",
    edition: 1,
    maxSupply: 80,
  },
  {
    id: 5,
    side: "White",
    material: "Gold",
    piece: "Bishop",
    rarity: "VeryRare",
    edition: 1,
    maxSupply: 15,
  },
  {
    id: 6,
    side: "Black",
    material: "Gold",
    piece: "Bishop",
    rarity: "VeryRare",
    edition: 1,
    maxSupply: 15,
  },
  {
    id: 7,
    side: "White",
    material: "Platinum",
    piece: "Rook",
    rarity: "VeryRare",
    edition: 1,
    maxSupply: 10,
  },
  {
    id: 8,
    side: "Black",
    material: "Platinum",
    piece: "Rook",
    rarity: "VeryRare",
    edition: 1,
    maxSupply: 10,
  },
  {
    id: 9,
    side: "White",
    material: "Diamond",
    piece: "Queen",
    rarity: "Mythic",
    edition: 1,
    maxSupply: 1,
  },
  {
    id: 10,
    side: "Black",
    material: "Diamond",
    piece: "Queen",
    rarity: "Mythic",
    edition: 1,
    maxSupply: 1,
  },
  {
    id: 11,
    side: "White",
    material: "Diamond",
    piece: "King",
    rarity: "Mythic",
    edition: 1,
    maxSupply: 1,
  },
  {
    id: 12,
    side: "Black",
    material: "Diamond",
    piece: "King",
    rarity: "Mythic",
    edition: 1,
    maxSupply: 1,
  },
  {
    id: 13,
    side: "White",
    material: "Platinum",
    piece: "Queen",
    rarity: "Mythic",
    edition: 1,
    maxSupply: 2,
  },
  {
    id: 14,
    side: "White",
    material: "Platinum",
    piece: "Queen",
    rarity: "Mythic",
    edition: 2,
    maxSupply: 2,
  },
  {
    id: 15,
    side: "Black",
    material: "Platinum",
    piece: "King",
    rarity: "Mythic",
    edition: 1,
    maxSupply: 2,
  },
  {
    id: 16,
    side: "Black",
    material: "Platinum",
    piece: "King",
    rarity: "Mythic",
    edition: 2,
    maxSupply: 2,
  },
  {
    id: 17,
    side: "White",
    material: "Diamond",
    piece: "Pawn",
    rarity: "Common",
    edition: 1,
    maxSupply: 100,
  },
  {
    id: 18,
    side: "Black",
    material: "Diamond",
    piece: "Knight",
    rarity: "Rare",
    edition: 1,
    maxSupply: 20,
  },
  {
    id: 19,
    side: "White",
    material: "Silver",
    piece: "Bishop",
    rarity: "VeryRare",
    edition: 1,
    maxSupply: 20,
  },
  {
    id: 20,
    side: "Black",
    material: "Gold",
    piece: "Rook",
    rarity: "VeryRare",
    edition: 1,
    maxSupply: 15,
  },
] as const;

export type TestnetCollectible =
  (typeof testnetCollection)[number];
